In [83]:
import numpy as np

In [84]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2D10 = mat2D * 10

In [85]:
print(f"Matriks 1D :\n {mat1D}")
print(f"Matriks 1D indeks ke 7:{mat1D[7]}")
print(f"Matriks 1D * 10 :\n {mat1D * 10}")

Matriks 1D :
 [1 2 3 4 5 6 7 8 9]
Matriks 1D indeks ke 7:8
Matriks 1D * 10 :
 [10 20 30 40 50 60 70 80 90]


In [86]:
print(f"Matriks 2D :\n {mat2D}")
print(f"Matriks 2D * 10 :\n {mat2D * 10}")
print(mat2D10[0])
print(mat2D10[0][2])

Matriks 2D :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Matriks 2D * 10 :
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[10 20 30]
30


In [87]:
print(mat1D.shape)
print(mat2D.shape)

(9,)
(4, 3)


In [88]:
print(f"Ukuran dari mat1D adalah : {mat1D.size}")
print(f"Ukuran dari mat2D adalah : {mat2D.size}")

Ukuran dari mat1D adalah : 9
Ukuran dari mat2D adalah : 12


In [89]:
#special matrix
mZero = np.zeros((3,3))
mOne = np.ones((3,3))
mFull = np.full((4,4),7) #Membuat array ukuran 4x4 diisi dengan nilai 7
mIdentity = np.eye((4))
mFRandom1D = np.random.rand(5)
mFRandom2D = np.random.rand(3,3)
mIRandom1D = np.random.randint(10,100,size=5)
mIRandom2D = np.random.randint(10,100,size=(4,4))

print(f"Matriks mZero :\n {mZero}")
print(f"Matriks mOne :\n {mOne}")
print(f"Matriks mFull :\n {mFull}")
print(f"Matriks mIdentity :\n {mIdentity}")
print(f"Matriks mFRandom1D :\n {mFRandom1D}")
print(f"Matriks mFRandom2D :\n {mFRandom2D}")
print(f"Matriks mIRandom1D :\n {mIRandom1D}")
print(f"Matriks mIRandom2D :\n {mIRandom2D}")

Matriks mZero :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriks mOne :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matriks mFull :
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Matriks mIdentity :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriks mFRandom1D :
 [0.71823284 0.10534398 0.72203126 0.2023977  0.17869205]
Matriks mFRandom2D :
 [[0.983787   0.54913781 0.89108292]
 [0.02041428 0.25962971 0.33299127]
 [0.34769134 0.4743517  0.29480483]]
Matriks mIRandom1D :
 [84 95 36 15 79]
Matriks mIRandom2D :
 [[34 15 54 77]
 [21 24 16 74]
 [85 32 73 50]
 [86 10 44 70]]


In [90]:
#Mengubah bentuk Array
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
mshape = data.reshape((9,1))
mFlat = data.flatten()

print(f"Matriks Data :\n {data}")
print(f"Matriks Reshape :\n {mshape}")
print(f"Matriks mFlat :\n {mFlat}")

Matriks Data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks Reshape :
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Matriks mFlat :
 [1 2 3 4 5 6 7 8 9]


In [91]:
#Deskriptif Statistik
x = np.array([1,2,3,4])
y = np.array([2,5,7,9])

#Menghitung dot product
r1 = np.dot(x,y)
r2 = np.add(x,y)

print(f"Hasil dari dot product: {r1}")
print(f"Hasil penjumlahan matriks: {r2}")
print(f"Nilai minimum: {y.min()}")
print(f"Nilai maksimum: {y.max()}")
print(f"Nilai ratarata: {y.mean()}")
print(f"Nilai total: {y.sum()}")
print(f"Nilai deviasi: {y.std()}")

Hasil dari dot product: 69
Hasil penjumlahan matriks: [ 3  7 10 13]
Nilai minimum: 2
Nilai maksimum: 9
Nilai ratarata: 5.75
Nilai total: 23
Nilai deviasi: 2.5860201081971503


In [92]:
#Filtering
nilaiPemrograman = np.array([100,90,100,80,50,50,50,40])
#Tampilkan nilai pemrograman yang lebih dari 50-> LULUS
#Berapakah jumlah mahasiswa yang lulus
jmLulus = nilaiPemrograman[nilaiPemrograman > 50]

print(jmLulus)
print(f"Mahasiswa yang lulus sebanyak: {jmLulus.size}")
print(f"Mahasiswa yang tidak lulus sebanyak: {nilaiPemrograman.size-jmLulus.size}")

[100  90 100  80]
Mahasiswa yang lulus sebanyak: 4
Mahasiswa yang tidak lulus sebanyak: 4


In [93]:
<b>Project Generate Data</b>
<br>
Buatlah 1000 Data customer CC, yang akan digunakan untuk prediksi atau klasifikasi yaitu:
    <ol>
        <li>Usia: 17 - 68</li>
        <li>Gender L/P:</li>
        <li>Transaksi PerBulan : 0-50</li>
        <li>Pembayaran: Buruk, Sedang, Bagus</li>
    </ol>
</br>

SyntaxError: invalid syntax (4229739130.py, line 1)

In [101]:
import numpy as np
import pandas as pd
jmlData = 10
usia = np.random.randint(17,61,size=jmlData)
gender = np.random.choice(['L','P'],size=jmlData)
transaksi = np.random.randint(0,51,size=jmlData)
pembayaran = np.random.choice(['Buruk','Bagus','Sedang'],size=jmlData)

df = pd.DataFrame({
    'usia' : usia,
    'gender' : gender,
    'transaksi' : transaksi,
    'pembayaran' : pembayaran
})

print(df)
print(df.info()) #Menampilkan karakteristik data
print(df.head()) #Menampilkan isi tabel 5 baris pertama
#tampilkan usia yang paling muda dan tua
print(f"Usia Customer Termuda: {df['usia'].min()}")
print(f"Usia Customer Tertua: {df['usia'].max()}")
#Tampilkan jumlah customer yang Laki laki
jmlL = df[df['gender']=='L']
print(f"Jumlah Customer Laki-Laki: {jmlL.size/4}")
print(f"Jumlah Customer Laki-Laki: {jmlL['gender'].size}")
df.to_csv("dataCustomer.csv")

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject